################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
obj/local/armeabi/objs-debug/game_shared/hellocpp \
obj/local/armeabi/objs-debug/game_shared/__/__/__/extensions/GUI/CCScrollView \
obj/local/armeabi/objs-debug/game_shared/__/__/Classes \
obj/local/armeabi/objs-debug/cpufeatures \
obj/local/armeabi/objs-debug/cocosdenshion_static/opensl \
obj/local/armeabi/objs-debug/cocosdenshion_static/jni \
obj/local/armeabi/objs-debug/cocosdenshion_static \
obj/local/armeabi/objs-debug/cocos_extension_static/spine \
obj/local/armeabi/objs-debug/cocos_extension_static/physics_nodes \
obj/local/armeabi/objs-debug/cocos_extension_static/network \
obj/local/armeabi/objs-debug/cocos_extension_static/LocalStorage \
obj/local/armeabi/objs-debug/cocos_extension_static/GUI/CCScrollView \
obj/local/armeabi/objs-debug/cocos_extension_static/GUI/CCEditBox \
obj/local/armeabi/objs-debug/cocos_extension_static/GUI/CCControlExtension \
obj/local/armeabi/objs-debug/cocos_extension_static/Components \
obj/local/armeabi/objs-debug/cocos_extension_static/CCBReader \
obj/local/armeabi/objs-debug/cocos_extension_static/CCArmature/utils \
obj/local/armeabi/objs-debug/cocos_extension_static/CCArmature/physics \
obj/local/armeabi/objs-debug/cocos_extension_static/CCArmature/external_tool/Json/lib_json \
obj/local/armeabi/objs-debug/cocos_extension_static/CCArmature/external_tool/Json \
obj/local/armeabi/objs-debug/cocos_extension_static/CCArmature/external_tool \
obj/local/armeabi/objs-debug/cocos_extension_static/CCArmature/display \
obj/local/armeabi/objs-debug/cocos_extension_static/CCArmature/datas \
obj/local/armeabi/objs-debug/cocos_extension_static/CCArmature/animation \
obj/local/armeabi/objs-debug/cocos_extension_static/CCArmature \
obj/local/armeabi/objs-debug/cocos_extension_static/AssetsManager \
obj/local/armeabi/objs-debug/cocos2dx_static/touch_dispatcher \
obj/local/armeabi/objs-debug/cocos2dx_static/tilemap_parallax_nodes \
obj/local/armeabi/objs-debug/cocos2dx_static/textures \
obj/local/armeabi/objs-debug/cocos2dx_static/text_input_node \
obj/local/armeabi/objs-debug/cocos2dx_static/support/zip_support \
obj/local/armeabi/objs-debug/cocos2dx_static/support/user_default \
obj/local/armeabi/objs-debug/cocos2dx_static/support/tinyxml2 \
obj/local/armeabi/objs-debug/cocos2dx_static/support/image_support \
obj/local/armeabi/objs-debug/cocos2dx_static/support/data_support \
obj/local/armeabi/objs-debug/cocos2dx_static/support/component \
obj/local/armeabi/objs-debug/cocos2dx_static/support \
obj/local/armeabi/objs-debug/cocos2dx_static/sprite_nodes \
obj/local/armeabi/objs-debug/cocos2dx_static/shaders \
obj/local/armeabi/objs-debug/cocos2dx_static/script_support \
obj/local/armeabi/objs-debug/cocos2dx_static/platform \
obj/local/armeabi/objs-debug/cocos2dx_static/platform/android/jni \
obj/local/armeabi/objs-debug/cocos2dx_static/platform/android \
obj/local/armeabi/objs-debug/cocos2dx_static/particle_nodes \
obj/local/armeabi/objs-debug/cocos2dx_static/misc_nodes \
obj/local/armeabi/objs-debug/cocos2dx_static/menu_nodes \
obj/local/armeabi/objs-debug/cocos2dx_static/layers_scenes_transitions_nodes \
obj/local/armeabi/objs-debug/cocos2dx_static/label_nodes \
obj/local/armeabi/objs-debug/cocos2dx_static/keypad_dispatcher \
obj/local/armeabi/objs-debug/cocos2dx_static/kazmath/src \
obj/local/armeabi/objs-debug/cocos2dx_static/kazmath/src/GL \
obj/local/armeabi/objs-debug/cocos2dx_static/effects \
obj/local/armeabi/objs-debug/cocos2dx_static/draw_nodes \
obj/local/armeabi/objs-debug/cocos2dx_static \
obj/local/armeabi/objs-debug/cocos2dx_static/cocoa \
obj/local/armeabi/objs-debug/cocos2dx_static/base_nodes \
obj/local/armeabi/objs-debug/cocos2dx_static/actions \
obj/local/armeabi/objs-debug/chipmunk_static/src \
obj/local/armeabi/objs-debug/chipmunk_static/src/constraints \
obj/local/armeabi/objs-debug/box2d_static/Rope \
obj/local/armeabi/objs-debug/box2d_static/Dynamics \
obj/local/armeabi/objs-debug/box2d_static/Dynamics/Joints \
obj/local/armeabi/objs-debug/box2d_static/Dynamics/Contacts \
obj/local/armeabi/objs-debug/box2d_static/Common \
obj/local/armeabi/objs-debug/box2d_static/Collision \
obj/local/armeabi/objs-debug/box2d_static/Collision/Shapes \
obj/local/armeabi/objs/game_shared/hellocpp \
obj/local/armeabi/objs/game_shared/__/__/Classes \
obj/local/armeabi/objs/cpufeatures \
obj/local/armeabi/objs/cocosdenshion_static/opensl \
obj/local/armeabi/objs/cocosdenshion_static/jni \
obj/local/armeabi/objs/cocosdenshion_static \
obj/local/armeabi/objs/cocos_extension_static/spine \
obj/local/armeabi/objs/cocos_extension_static/physics_nodes \
obj/local/armeabi/objs/cocos_extension_static/network \
obj/local/armeabi/objs/cocos_extension_static/LocalStorage \
obj/local/armeabi/objs/cocos_extension_static/GUI/CCScrollView \
obj/local/armeabi/objs/cocos_extension_static/GUI/CCEditBox \
obj/local/armeabi/objs/cocos_extension_static/GUI/CCControlExtension \
obj/local/armeabi/objs/cocos_extension_static/Components \
obj/local/armeabi/objs/cocos_extension_static/CCBReader \
obj/local/armeabi/objs/cocos_extension_static/CCArmature/utils \
obj/local/armeabi/objs/cocos_extension_static/CCArmature/physics \
obj/local/armeabi/objs/cocos_extension_static/CCArmature/external_tool/Json/lib_json \
obj/local/armeabi/objs/cocos_extension_static/CCArmature/external_tool/Json \
obj/local/armeabi/objs/cocos_extension_static/CCArmature/external_tool \
obj/local/armeabi/objs/cocos_extension_static/CCArmature/display \
obj/local/armeabi/objs/cocos_extension_static/CCArmature/datas \
obj/local/armeabi/objs/cocos_extension_static/CCArmature/animation \
obj/local/armeabi/objs/cocos_extension_static/CCArmature \
obj/local/armeabi/objs/cocos_extension_static/AssetsManager \
obj/local/armeabi/objs/cocos2dx_static/touch_dispatcher \
obj/local/armeabi/objs/cocos2dx_static/tilemap_parallax_nodes \
obj/local/armeabi/objs/cocos2dx_static/textures \
obj/local/armeabi/objs/cocos2dx_static/text_input_node \
obj/local/armeabi/objs/cocos2dx_static/support/zip_support \
obj/local/armeabi/objs/cocos2dx_static/support/user_default \
obj/local/armeabi/objs/cocos2dx_static/support/tinyxml2 \
obj/local/armeabi/objs/cocos2dx_static/support/image_support \
obj/local/armeabi/objs/cocos2dx_static/support/data_support \
obj/local/armeabi/objs/cocos2dx_static/support/component \
obj/local/armeabi/objs/cocos2dx_static/support \
obj/local/armeabi/objs/cocos2dx_static/sprite_nodes \
obj/local/armeabi/objs/cocos2dx_static/shaders \
obj/local/armeabi/objs/cocos2dx_static/script_support \
obj/local/armeabi/objs/cocos2dx_static/platform \
obj/local/armeabi/objs/cocos2dx_static/platform/android/jni \
obj/local/armeabi/objs/cocos2dx_static/platform/android \
obj/local/armeabi/objs/cocos2dx_static/particle_nodes \
obj/local/armeabi/objs/cocos2dx_static/misc_nodes \
obj/local/armeabi/objs/cocos2dx_static/menu_nodes \
obj/local/armeabi/objs/cocos2dx_static/layers_scenes_transitions_nodes \
obj/local/armeabi/objs/cocos2dx_static/label_nodes \
obj/local/armeabi/objs/cocos2dx_static/keypad_dispatcher \
obj/local/armeabi/objs/cocos2dx_static/kazmath/src \
obj/local/armeabi/objs/cocos2dx_static/kazmath/src/GL \
obj/local/armeabi/objs/cocos2dx_static/effects \
obj/local/armeabi/objs/cocos2dx_static/draw_nodes \
obj/local/armeabi/objs/cocos2dx_static \
obj/local/armeabi/objs/cocos2dx_static/cocoa \
obj/local/armeabi/objs/cocos2dx_static/base_nodes \
obj/local/armeabi/objs/cocos2dx_static/actions \
obj/local/armeabi/objs/chipmunk_static/src \
obj/local/armeabi/objs/chipmunk_static/src/constraints \
obj/local/armeabi/objs/box2d_static/Rope \
obj/local/armeabi/objs/box2d_static/Dynamics \
obj/local/armeabi/objs/box2d_static/Dynamics/Joints \
obj/local/armeabi/objs/box2d_static/Dynamics/Contacts \
obj/local/armeabi/objs/box2d_static/Common \
obj/local/armeabi/objs/box2d_static/Collision \
obj/local/armeabi/objs/box2d_static/Collision/Shapes \
jni/hellocpp \
Classes \

